# This is a basic workflow to help you get started with Actions

name: PR Notification

on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        shell: bash
        env:
          DINGTALK_URL: ${{ secrets.DINGTALK_URL_TGF }}
          DINGTALK_ID: ${{ secrets.DINTTALK_ID_TGF }}
        run: |
          PR_AUTHOR="${{ github.event.pull_request.user.login }}"
          PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          TEXT="{\"content\":\"$PR_AUTHOR 提交了文档 PR https://github.com/AlipayDocs/open-docs/pull/$PR_NUMBER/files @$DINGTALK_ID\"}"
          AT="{\"atDingtalkIds\":[\"$DINGTALK_ID\"]}"
          curl -sS "$DINGTALK_URL" -H 'Content-Type: application/json' -d "{\"msgtype\":\"text\",\"text\":$TEXT,\"at\":$AT}"
          echo
