# This is a basic workflow to help you get started with Actions

name: PR Notification

on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        shell: bash
        env:
          DINGTALK_URL: ${{ secrets.DINGTALK_URL_TGF }}
        run: |
          PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          curl -sS "$DINGTALK_URL" -H 'Content-Type: application/json' -d '{"msgtype":"text","text":{"content":"Hello from github #'"$PR_NUMBER"'"}}'
          echo
